spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///bbs?serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  mail:
    username: xxx@sina.com
    password: xxx
    host: smtp.sina.com
  redis:
    host: 192.168.2.234
    port: 6379
  profiles:
    active: dev



mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    map-underscore-to-camel-case: true
    local-cache-scope: statement
  type-aliases-package: com.own.entity

pagehelper:
  reasonable: true
  offset-as-page-num: true
  helper-dialect: mysql

logging:
  level:
    com.own: debug
  file:
    path: e:/log/
    max-history: 15
    max-size: 20MB

server:
  servlet:
    context-path: /bbs

